.macos_saas_runners:
  tags:
    - shared-macos-amd64
  image: macos-11-xcode-13

variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - build

build_project:
  extends:
    - .macos_saas_runners
  stage: build
  script:
    - cp "$DEV_TEAM_FILE" Xcode-config/DEVELOPMENT_TEAM.xcconfig
    - xcodebuild -workspace "./Cog.xcodeproj/project.xcworkspace" -scheme Cog -configuration Release -derivedDataPath "./CogBuilds" CODE_SIGNING_ALLOWED=NO ONLY_ACTIVE_ARCH=NO build
    - ditto -c -k --sequesterRsrc --keepParent  "./CogBuilds/Build/Products/Release/Cog.app" "./CogBuilds/Cog.app.zip" 
  artifacts:
    paths: 
    - ./CogBuilds/Cog.app.zip
    expire_in: 1 week
